---
- name: Linux Installer
  hosts: all
  collections:
    - community.general
  roles:
    - role: install
      ansible_become_method: su
      become: true
      become_user: root
    - role: install_rust
      become: false
      remote_user: "{{ setup_user }}"
    - role: cargo_install
      become: false
      remote_user: "{{ setup_user }}"
    - role: dotfile
      become: false
      ansible_become_method: su
