---
- name: Install DWM Dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    allowerasing: true
  loop: "{{ dwm_packages }}"
  become: true
  become_user: root
  become_method: su

- name: Clone VirtualDWM
  ansible.builtin.git:
    repo: "{{ dwm_repo }}"
    dest: "{{ dwm_location }}"
    version: "{{ dwm_branch }}"

- name: Build DWM Binary (Dev)
  ansible.builtin.command:
    chdir: "{{ dwm_location }}"
    cmd: bear -- make
    creates: "{{ dwm_location}}/dwm"

- name: Build slstatus Binary (Dev)
  ansible.builtin.command:
    chdir: "{{ dwm_location }}/slstatus"
    cmd: bear -- make
    creates: "{{ dwm_location}}/slstatus/slstatus"

- name: Install DWM Binary To Global Path for SDDM
  ansible.builtin.command:
    chdir: "{{ dwm_location }}"
    cmd: make install
    creates: "/usr/local/bin/dwm"
  become: true
  become_user: root
  become_method: su

- name: Add rofi config to config dir
  ansible.builtin.copy:
    src: "{{ dwm_location }}/config/rofi
    dest: "/home/{{ ansible_user }}/.config/"
    remote_src: true

- name: Install slstatus Binary To Global Path for SDDM
  ansible.builtin.command:
    chdir: "{{ dwm_location }}/slstatus"
    cmd: make install
    creates: "/usr/local/bin/slstatus"
  become: true
  become_user: root
  become_method: su

- name: Install SDDM Conf
  ansible.builtin.copy:
    src: sddm.conf
    dest: /etc/sddm.conf
    mode: '0644'
    owner: root
    group: root
  become: true
  become_user: root
  become_method: su


- name: Ensure Local Path Exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"

- name: Copy DWM Binary to Local Path
  ansible.builtin.copy:
    src: "{{ dwm_location }}/dwm"
    dest: "{{ ansible_env.HOME }}/.local/bin/dwm"
    mode: "0755"
    remote_src: true

- name: Copy slstatus Binary to Local Path
  ansible.builtin.copy:
    src: "{{ dwm_location }}/slstatus/slstatus"
    dest: "{{ ansible_env.HOME }}/.local/bin/slstatus"
    mode: "0755"
    remote_src: true

- name: Setup xinitrc
  ansible.builtin.template:
    src: xinitrc.j2
    dest: "{{ ansible_env.HOME }}/.xinitrc"

- name: Set The Graphical Target as Default
  block:
    - name: "Get current systemd default"
      ansible.builtin.command: "systemctl get-default"
      changed_when: false
      register: systemdefault

    - name: "Set default to graphical target"
      ansible.builtin.command: "systemctl set-default graphical.target"
      when: "'graphical' not in systemdefault.stdout"
      changed_when: true
  become: true
  become_user: root
  become_method: su

