---
- name: Verify that your dotfile directory exists
  stat:
    path: "{{ dotfile_local_location }}"
  register: dotfile_dir_info

- name: Create the dotfile directory if it doesn't exist
  file:
    path: "{{ dotfile_local_location }}"
    state: directory
    mode: "0755"

- name: Clone git dotfiles repo
  git:
    repo: "{{ dotfile_repo }}"
    dest: "{{ dotfile_local_location }}"
    version: "{{ dotfile_repo_branch }}"
  become: false

- name: Verify that your HOME/.config directory exists
  stat:
    path: "{{ lookup('ansible.builtin.env', 'HOME') + '/.config' }}"
  register: config_dir

- name: Create the config directory if it doesn't exist
  file:
    path: "{{ config_dir }}"
    state: directory
    mode: "0755"

# Use custom module for this, this is bunk
- name: Use GNU Stow to place all dotfiles
  command: stow -d {{ dotfile_local_location }}/ -t ~/ {{ item }}
  loop: "{{ dotfile_packages }}"

- name: Set ZSH as default shell
  become: true
  user:
    name: "{{ setup_user }}"
    shell: /usr/bin/zsh

- name: Download zap installer
  uri:
    url: https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh
    dest: /tmp/install.zsh

- name: Install ZAP ZSH Plugin
  command: /usr/bin/zsh /tmp/install.sh --keep --branch release-v1

- name: Clone getnf repo
  git:
    repo: "https://github.com/ronniedroid/getnf"
    dest: "{{ lookup('ansible.builtin.env', 'HOME') + '/Code' }}"