---
dnf_packages:
  - btop
  - code
  - exa
  - fd-find
  - ffmpeg
  - flatpak
  - fzf
  - gcc
  - g++
  - git
  - git-filter-repo
  - neofetch
  - neovim
  - python3-pip
  - pipx
  - procs
  - ranger
  - stow
  - tmux
  - unzip # necessary for Mason
  - zsh
  - zoxide
  # COPR
  - wezterm
  # Cargo
  # - bat
  # - duf
  # - ripgrep

flatpaks:
  - obsidian
