---
dnf_packages:
  - gawk
  - eza
  - fd-find
  - ffmpeg
  - flatpak
  - fzf
  - gcc
  - g++
  - git
  - git-filter-repo
  - neofetch
  - neovim
  - python3-pip
  - pipx
  - ranger
  - stow
  - tmux
  - unzip # necessary for Mason
  - zsh
  - zoxide

gui:
  # COPR
  - wezterm
  - code
flatpaks:
  - obsidian
