---
dwm_packages:
  - libX11-devel
  - libXinerama-devel
  - libXft-devel
  - imlib2-devel
  - libxcb-devel
  - unzip
  - flameshot
  - lxappearance
  - feh
  - mate-polkit
  - rofi
  - picom
  - amixer
  - thunar
  - flameshot
  - synergy
  - dunst
  - bear
  - sddm
  - sddm-kcm
  - xrandr
  - xorg-x11-server-Xorg
