---
# tasks file for installing packages
- name: Add RPM Fusion Free Repo Key
  rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPM Fusion Free Repo
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPM Fustion NonFree Repo Key
  rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Add RPM Fusion Free Repo
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_distribution == 'Fedora'

- name: Import VSCode Repo Key
  rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"

- name: Add VSCode Repo
  yum_repository:
    name: code
    description: Repo with VSCode Package
    baseurl: "https://packages.microsoft.com/yumrepos/vscode"
    gpgcakey: "https://packages.microsoft.com/keys/microsoft.asc"

- name: Add Wezterm COPR Repo
  community.general.copr:
    state: enabled
    name: wezfurlong/wezterm-nightly

- name: Update DNF Cache
  dnf:
    name: "*"
    state: latest

- name: Install DNF Packages
  dnf:
    name: "{{ item }}"
    state: present
    allowerasing: true
  loop: "{{ dnf_packages }}"
  ignore_errors: true

- name: Install NVM
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install Node using NVM
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install node
      environment:
        HOME: "{{ ansible_env.HOME }}"
